services:
  app:
    build: .
    container_name: ms_authentication_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: postgre-sql
      ENV_SPRING_DATASOURCE_URL: jdbc:postgresql://ms-authentication-db:5432/authentication_users_db
      ENV_SPRING_DATASOURCE_USERNAME: adim
      ENV_SPRING_DATASOURCE_PASSWORD: sua_Senha
      ENV_SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      ENV_SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    entrypoint: [ "sh", "-c", "sleep 90 && java -jar ms-authentication.jar" ]
    networks:
      - ms-authentication-network

  db:
    image: postgres:latest
    container_name: ms-authentication-db
    environment:
      POSTGRES_DB: authentication_users_db
      POSTGRES_USER: adim
      POSTGRES_PASSWORD: sua_Senha
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ms-authentication-network

networks:
  ms-authentication-network:
    driver: bridge

volumes:
  postgres-data:
