spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_users_db
    username: adim
    password: sua_Senha
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
